### ISSUE TITLE
Passing wrong value in Magento 1 multi store setup

### ISSUE THREAD

**Issue by nikolapavlovic994** [vippsas/vipps-magento-v1#2]
We have setup 2 stores in our Magneto 1 installation. 
Norwegian  store works as intended. Problem happens on English store. Vipps is getting totals in US Dollars but converts it to NOK. This means that module is ignoring the currency setup.

**Comment by nikolapavlovic994** [comment]
@cloveras is this module still maintained or should we look for replacements ?

**Comment by voleye** [comment]
Hi @nikolapavlovic994 ,

All payments in Vipps is in NOK. Any conversions from other currencies must be done before the API calls to Vipps. Do you see any issue while handling a conversion?

**Comment by nikolapavlovic994** [comment]
We have two stores and when we're passing from US store it is in $, for example product that costs 200$ is passed to Vipps as 200 NOK. That is the issue we're facing right now.

**Comment by voleye** [comment]
@nikolapavlovic994 correct me if I am wrong, but is it possible to pay with Vipps in US? I should not be possible. Or do you have a Norwegian customers and Norwegian store but the currency you are using is USD? Is it could case?

**Comment by nikolapavlovic994** [comment]
It's Norwegian multi store, and one of the currencies is USD. So when customer tries to buy in USD the price is wrong. Vipps is using then USD price instead of NOK.

**Comment by cloveras** [comment]
Hi @nikolapavlovic994 

Vipps only supports NOK. Vipps does not support other currencies. If you have an amount in USD in the US store, the USD amount will be assumed to be in NOK by Vipps. 

I don't know the Magento details around this, so I will leave that to @voleye. 

Christian, Vipps

**Comment by voleye** [comment]
@nikolapavlovic994 thanks for detailed description. Yes, seems it is an issue with currency converting, we will take a look at it and get back to you soon

**Comment by nikolapavlovic994** [comment]
@voleye thank you so much.

**Comment by nikolapavlovic994** [comment]
Any progress on this so far ?
