### ISSUE TITLE
Cancellation in backend

### ISSUE THREAD

**Issue by thomas-thaulow** [vippsas/vipps-magento-v1#6]
Hello, I am under the impression that the Vipps module supported refund when sending credit memo in backend. However I might be wrong. 

We have updated our Vipps module to the newest release and since we struggle with timeout on order quote, so we had to adjust timeout higher to make Vipps checkout work again. Has anyone else struggled similar with the newest update?

In addition I only see the Offline Refund button now, so I wonder if thats due to the fact its not working or if there has never been support for refund in backend. 

Magneto 1.9.3.4 and Vipps newest version from todays date.

**Comment by ed007m** [comment]
Hi @thomas-thaulow ,
Sorry for the very late response. We have updated the Vipps module and changed the order flow functionality in the latest version. The refund feature will work there. Please try it out and let me know if it solves it.
